insert into card_library (name, kind, tier, cost, effect, rules, flavor, review) values
-- 40 commons
('Bump and Run', 'Enchantment', 'common', 1, 'custom', 'If your golfer finishes in the top 20, earn a 5% earnings bonus.', 'Low, ugly, effective.', true),
('Cold Putter', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer makes no birdies in round 2, they take a 10% earnings penalty.', 'Dead hands.', true),
('Dew Sweeper', 'Enchantment', 'common', 1, 'custom', 'If your golfer shoots under par in round 1, earn a 5% earnings bonus.', 'First off. First in the bar.', true),
('Lost in the Trees', 'Curse', 'common', 1, 'custom', 'Choose an opponent. Their golfer takes a 1 stroke penalty in the round he makes his first double bogey. No double bogey, no penalty.', 'Punch out. Pray.', true),
('Yardage Book', 'Gear', 'common', 1, 'custom', 'If your golfer finishes within 3 strokes of the winner, earn a 5% earnings bonus.', 'Every number but the one that matters.', true),
('Hot Streak', 'Enchantment', 'common', 1, 'custom', 'If your golfer made the cut in his previous start, earn a 5% earnings bonus this week.', 'Ride it till it bucks you.', true),
('Cold Streak', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer missed the cut in his previous start, they take a 10% earnings penalty this week.', 'Same swing, new week, same problem.', true),
('Rules Official', 'Instant', 'common', 1, 'custom', 'Cancel one earnings penalty of 5% or less applied to you this tournament.', '"Let me get the book."', true),
('Second Cut', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer shoots over par in round 3, they take a 5% earnings penalty.', 'Moving day, wrong direction.', true),
('Chip-In', 'Enchantment', 'common', 1, 'custom', 'Earn a $30,000 bonus the first time your golfer shoots 66 or better this tournament.', 'Never a doubt. Pure luck.', true),
('Cash Game', 'Enchantment', 'common', 1, 'custom', 'Earn $5,000 for every place your golfer finishes better than 50th, up to $200,000.', 'Skins.', true),
('Bogey Train', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer makes three bogeys in a row in any round, they take a 10% earnings penalty.', 'All aboard.', true),
('Scrambler', 'Enchantment', 'common', 1, 'custom', 'If your golfer shoots par or better in a round where he made a double bogey, earn a 6% earnings bonus.', 'Ugly, but it counts.', true),
('Wrong Ball', 'Curse', 'common', 1, 'custom', 'Choose an opponent. Their golfer takes a 2 stroke penalty in round 1 unless he shoots under par that round.', 'Whose Pro V1 is this?', true),
('Good-Good', 'Instant', 'common', 1, 'custom', 'Your golfer''s round 2 score improves by 1 stroke.', 'You don''t miss that. I don''t miss that.', true),
('Center Cut', 'Instant', 'common', 1, 'custom', 'Your golfer''s round 3 score improves by 1 stroke.', 'Dead center. Never a doubt.', true),
('Bad Lie', 'Curse', 'common', 1, 'custom', 'Choose an opponent. Their golfer takes a 1 stroke penalty in round 3.', 'Divot. Of course.', true),
('Momentum', 'Enchantment', 'common', 1, 'custom', 'If your golfer''s score improves every round, earn a 12% earnings bonus.', 'Trending.', true),
('Sleeping on the Lead', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer leads after round 3 and does not win, they take a 10% earnings penalty.', 'Long night.', true),
('Big Sunday', 'Enchantment', 'common', 1, 'custom', 'If your golfer''s round 4 is his best round of the week, earn a 6% earnings bonus.', 'Saved the good stuff.', true),
('Bounce Back', 'Enchantment', 'common', 1, 'custom', 'Earn $15,000 each time your golfer follows a bogey or worse with a birdie or better, up to $150,000.', 'Shake it off.', true),
('Water Ball', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer makes a double bogey or worse on a par 3, they take a 5% earnings penalty.', 'Splash.', true),
('Par Machine', 'Enchantment', 'common', 1, 'custom', 'If your golfer makes 50 or more pars this tournament, earn a 10% earnings bonus.', 'Boring wins.', true),
('Bird Watching', 'Enchantment', 'common', 1, 'custom', 'If your golfer makes 20 or more birdies this tournament, earn a 10% earnings bonus.', 'Count ''em.', true),
('Long Putt', 'Enchantment', 'common', 1, 'custom', 'Earn $10,000 for every hole your golfer plays under par on the back nine in round 4, up to $90,000.', 'Drain it.', true),
('Cold Front', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer shoots 75 or worse in any round, they take an 8% earnings penalty.', 'Layers.', true),
('Fairway Finder', 'Enchantment', 'common', 1, 'custom', 'If your golfer makes no double bogeys all tournament, earn an 8% earnings bonus.', 'Boring off the tee, rich on Sunday.', true),
('Job Security', 'Enchantment', 'common', 1, 'custom', 'If your golfer makes the cut, earn a $50,000 bonus.', 'Made it. Barely.', true),
('Late Withdrawal', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer withdraws or is disqualified, they take an additional $100,000 fine.', 'Back tightness.', true),
('Extra Holes', 'Enchantment', 'common', 1, 'custom', 'If your golfer plays in a playoff, earn a 10% earnings bonus.', 'Extra holes, extra money.', true),
('Thursday Hero', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer is in the top 5 after round 1 and finishes outside the top 20, they take a 10% earnings penalty.', 'Peaked early.', true),
('Steady Eddie', 'Enchantment', 'common', 1, 'custom', 'If all four of your golfer''s rounds are within 3 strokes of each other, earn an 8% earnings bonus.', 'Same guy, every day.', true),
('Free Drop', 'Instant', 'common', 1, 'custom', 'Cancel one stroke penalty applied to a partner of your choice this tournament.', 'Generous.', true),
('Amateur Hour', 'Curse', 'common', 1, 'custom', 'Choose an opponent. Their golfer takes a 1 stroke penalty in his worst round of the tournament.', 'Play like a member.', true),
('Marshal', 'Gear', 'common', 1, 'custom', 'Cards that hit a randomly chosen opponent cannot choose you this tournament.', '"Quiet, please."', true),
('Weekend Pass', 'Enchantment', 'common', 1, 'custom', 'If your golfer makes the cut, earn a $30,000 bonus. If he finishes in the top 10, make it $60,000.', 'See you Saturday.', true),
('Lip Out', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer misses the cut by exactly 1 stroke, they take a $50,000 fine.', 'So close.', true),
('Sunday Bag', 'Gear', 'common', 1, 'custom', 'Your next booster pack''s final card is drawn twice; you keep the higher tier.', 'Travel light. Hit big.', true),
('Front Nine Sprint', 'Enchantment', 'common', 1, 'custom', 'If your golfer plays the front nine under par in all four rounds, earn a 10% earnings bonus.', 'Fast start.', true),
('Out of Position', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer drops 10 or more places in round 4, they take a 10% earnings penalty.', 'Wrong side of the draw.', true),
-- 20 rares
('Moving Day', 'Enchantment', 'rare', 2, 'custom', 'If your golfer shoots the low round of the field in round 3, earn a 25% earnings bonus.', 'Saturday is for the bold.', true),
('Bad Draw', 'Curse', 'rare', 2, 'custom', 'Choose an opponent. Their golfer takes a 1 stroke penalty in every round he shoots over par.', 'Wrong side of the wave.', true),
('Course Whisperer', 'Enchantment', 'rare', 2, 'custom', 'If your golfer finishes in the top 10, earn a 15% earnings bonus.', 'He and the course have an understanding.', true),
('Hex', 'Curse', 'rare', 2, 'custom', 'Choose an opponent. Their golfer takes a 2 stroke penalty in round 4.', 'Old magic.', true),
('Insurance Policy', 'Enchantment', 'rare', 2, 'custom', 'If your golfer misses the cut, you receive the average prize money of all league picks this tournament instead.', 'The premiums were steep.', true),
('Shared Pick', 'Curse', 'rare', 2, 'custom', 'If any opponent picked the same golfer as you this tournament, they take a 25% earnings penalty.', 'Get your own guy.', true),
('Two-Way Miss', 'Curse', 'rare', 2, 'custom', 'Choose an opponent. For each round their golfer shoots 74 or worse, they take a 10% earnings penalty.', 'Left, then right, then trouble.', true),
('Rally Killer', 'Instant', 'rare', 2, 'custom', 'Choose an opponent whose golfer is inside the top 10 after round 3. Their golfer takes a 2 stroke penalty in round 4.', 'Back to the pack.', true),
('Second Wind', 'Enchantment', 'rare', 2, 'custom', 'If your golfer finishes better than his position after round 2, earn a 15% earnings bonus.', 'He''s not done.', true),
('Loot Bag', 'Gear', 'rare', 2, 'custom', 'Your next booster pack contains two extra cards, both at least Rare.', 'Heavy.', true),
('Tee Thief', 'Curse', 'rare', 2, 'custom', 'Choose an opponent. Next tournament they have 2 tees instead of 3.', 'Check your pockets.', true),
('Overtime', 'Enchantment', 'rare', 2, 'custom', 'Your Instant window stays open until the end of the tournament instead of closing at 8 PM on day 3.', 'The clock is a suggestion.', true),
('Bounty', 'Enchantment', 'rare', 2, 'custom', 'Name an opponent. If your golfer finishes ahead of theirs, you take 15% of their earnings.', 'Wanted.', true),
('Reverse Curse', 'Instant', 'rare', 2, 'custom', 'The next Curse played against you this tournament hits the player who cast it instead.', 'Look what you made me do.', true),
('Doubling Down', 'Enchantment', 'rare', 3, 'custom', 'If your golfer wins, earn a 50% earnings bonus. If he misses the cut, take a $250,000 fine.', 'All in.', true),
('Blackout', 'Curse', 'rare', 2, 'custom', 'Choose an opponent. Every Instant they play this tournament costs 1 extra tee.', 'Lights out.', true),
('Home Cooking', 'Enchantment', 'rare', 2, 'custom', 'If your golfer has won this event before, earn a 25% earnings bonus.', 'He knows the greens like his own kitchen.', true),
('Paperwork', 'Enchantment', 'rare', 2, 'custom', 'Your golfer''s prize money is calculated as if he finished one place higher.', 'Clerical error. In your favor.', true),
('Weather Eye', 'Enchantment', 'rare', 2, 'custom', 'If the field''s scoring average in any round is 73 or worse, earn a 15% earnings bonus.', 'He likes it ugly.', true),
('Hostile Crowd', 'Curse', 'rare', 2, 'custom', 'Choose an opponent. Their golfer takes a 1 stroke penalty in each of rounds 3 and 4.', 'They came for you.', true);
select tier, count(*) filter (where review) as needs_review, count(*) as active from card_library where not retired group by tier order by 1;
