insert into card_library (name, kind, tier, cost, effect, rules, flavor, review) values
('Gimme', 'Instant', 'common', 1, 'custom', 'Your golfer''s round 1 score improves by 1 stroke.', 'Inside the leather. Just pick it up.', true),
('Range Ball', 'Enchantment', 'common', 0, 'custom', 'Your golfer''s prize money is boosted 3% this tournament.', 'Cut, scuffed, striped, and still better than yours.', true),
('Sandbagger', 'Enchantment', 'common', 1, 'custom', 'If your golfer makes the cut but finishes outside the top 40, earn a $150,000 bonus.', 'Handicap? What handicap?', true),
('Cart Path Only', 'Curse', 'common', 1, 'custom', 'Choose an opponent. Their golfer loses 3% for every bogey in round 4, up to 15%.', 'Take a drop. And another.', true),
('Sunday Red', 'Enchantment', 'common', 1, 'custom', 'If your golfer posts the lowest round 4 among all league picks, earn a 10% bonus.', 'It was never about the shirt.', true),
('Greenside Bunker', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer bogeys the 18th hole on any day, they take a 5% penalty.', 'Plugged. Fried egg. Sunny side down.', true),
('The Yips', 'Curse', 'common', 1, 'custom', 'A randomly chosen opponent''s golfer takes a 1 stroke penalty in round 3.', 'It''s in your head. Now it''s in your hands.', true),
('Caddie''s Advice', 'Instant', 'common', 1, 'custom', 'Before lock, learn one opponent''s current pick.', '"Trust me. It''s a smooth eight."', true),
('Local Knowledge', 'Enchantment', 'common', 1, 'custom', 'If your golfer has won this event before, earn a 10% bonus.', 'He knows where the bodies are buried. Mostly his own.', true),
('Rain Delay', 'Instant', 'common', 1, 'custom', 'Play before lock. Everyone''s Instant window closes 8 hours early this week.', 'Horn blows. Beers open.', true),
('Weekend Warrior', 'Enchantment', 'common', 1, 'custom', 'If your golfer shoots under par in both weekend rounds, earn an 8% bonus.', 'Monday, he''s an accountant.', true),
('Practice Swing', 'Enchantment', 'common', 0, 'custom', 'Your next booster pack contains one extra Common.', 'Looked great. The real one didn''t.', true),
('Shank', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer makes a double bogey or worse this tournament, they lose 5%.', 'We don''t say the word.', true),
('Free Relief', 'Instant', 'common', 1, 'custom', 'Cancel one stroke penalty applied to your golfer this tournament.', 'Ground under repair. Allegedly.', true),
('Fore Left!', 'Curse', 'common', 0, 'custom', 'A randomly chosen opponent takes a 2% penalty.', 'Duck.', true),
('Birdie Juice', 'Enchantment', 'common', 1, 'custom', 'Earn $25,000 for every birdie your golfer makes in round 1, up to $200,000.', 'Flask of unknown origin.', true),
('Three-Putt', 'Curse', 'common', 1, 'custom', 'Choose an opponent. Their golfer takes a 1 stroke penalty in round 2.', 'Speed was good.', true),
('Tap-In', 'Enchantment', 'common', 1, 'custom', 'Your golfer''s round 4 score improves by 1 stroke.', 'Never up, never in. This one''s up.', true),
('Cut Line', 'Enchantment', 'common', 1, 'custom', 'If your golfer makes the cut on the number, earn a 15% bonus.', 'Living on the edge. Sleeping in the car.', true),
('Made the Bar', 'Enchantment', 'common', 1, 'custom', 'If your golfer misses the cut, earn $100,000 anyway.', 'The 19th hole pays out too.', true),
('Marker''s Error', 'Instant', 'common', 1, 'custom', 'Choose an opponent. Their golfer takes a 1 stroke penalty in round 1.', 'Sign here. And here. Oh.', true),
('Extra Tee', 'Gear', 'common', 0, 'custom', 'You have 4 tees this tournament instead of 3.', 'Found it in the cup holder.', true),
('Breakfast Ball', 'Gear', 'common', 1, 'custom', 'Your first card next tournament costs 1 tee less.', 'Nobody saw the first one.', true),
('Lift, Clean and Place', 'Enchantment', 'common', 1, 'custom', 'Your golfer''s worst round this tournament counts 1 stroke better.', 'Preferred lies. Preferred results.', true),
('Gallery Heckler', 'Curse', 'common', 1, 'custom', 'Choose an opponent. Their golfer takes a 1 stroke penalty in round 4.', '"MASHED POTATOES!"', true),
('Back Nine Charge', 'Enchantment', 'common', 1, 'custom', 'If your golfer finishes higher than he started round 4, earn an 8% bonus.', 'The tournament starts on the back nine Sunday.', true),
('Slow Play Warning', 'Curse', 'common', 1, 'custom', 'Choose an opponent. They cannot play Instants this tournament.', 'On the clock. In your place.', true),
('Sponsor''s Exemption', 'Enchantment', 'common', 1, 'custom', 'Your golfer''s prize money counts at the tournament multiplier plus 0.1.', 'Somebody''s nephew.', true),
('Pro-Am Hangover', 'Curse', 'common', 1, 'custom', 'A randomly chosen opponent''s golfer takes a 1 stroke penalty in round 1.', 'Wednesday was a long day.', true),
('Ham and Egg', 'Enchantment', 'common', 1, 'custom', 'Choose a partner. Whoever''s golfer earns less receives 10% of the other''s prize money.', 'One of us had to show up.', true),
('Fescue', 'Curse', 'common', 1, 'custom', 'Choose an opponent. Their golfer loses 4% for each round over par, up to 12%.', 'Found it. Wish I hadn''t.', true),
('Clubhouse Leader', 'Enchantment', 'common', 1, 'custom', 'Earn $75,000 for each completed round your golfer leads or co-leads.', 'Enjoy it. It''s early.', true),
('Provisional', 'Instant', 'common', 1, 'custom', 'If your golfer withdraws or is disqualified, you receive the average prize money of the league''s picks instead.', 'Just in case.', true),
('Grip It and Rip It', 'Enchantment', 'common', 1, 'custom', 'Earn $20,000 for every eagle your golfer makes this tournament.', 'Aim small, miss big.', true),
('Two-Club Wind', 'Curse', 'common', 1, 'custom', 'Choose an opponent. Each of their golfer''s over-par rounds counts 1 stroke worse, up to 2.', 'Hit the knockdown. Hit it again.', true),
('Course Record', 'Enchantment', 'common', 1, 'custom', 'If your golfer posts the low round of the day in any round, earn a 10% bonus.', 'Somebody check the scorecard.', true),
('Cart Girl', 'Enchantment', 'common', 0, 'custom', 'Earn a $50,000 bonus this tournament.', 'Transfusion. Two, actually.', true),
('Snowman', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer makes an 8 or worse on any hole, they lose 10%.', 'Frosty.', true),
('Even Par', 'Enchantment', 'common', 1, 'custom', 'If your golfer finishes the tournament at exactly even par, earn a 20% bonus.', 'Boring golf. Beautiful golf.', true),
('Trunk Slammer', 'Curse', 'common', 1, 'custom', 'Choose an opponent. If their golfer misses the cut, they take an extra $50,000 fine.', 'See you in Reno.', true);
select count(*) filter (where review) as needs_review, count(*) as total_active from card_library where not retired;
